nomade_admin/urls.py
from django.contrib import admin
from django.urls import path
from db_admin.views import PlaceListView

urlpatterns = [
    path('', PlaceListView.as_view(), name='place_list'),
]

db_admin/models.py
from django.db import models

class Place(models.Model):
    name = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    type = models.IntegerField(null=True, blank=True)
    quiet = models.BooleanField(null=True, blank=True)
    wifi = models.IntegerField(null=True, blank=True)
    outlet = models.BooleanField(null=True, blank=True)
    class Meta:
        db_table = 'places'

class Img(models.Model):
    path = models.CharField(max_length=100)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    class Meta:
        db_table = 'imgs'

db_admin/views.py
from django.views.generic import ListView
from .models import Place

class PlaceListView(ListView):
    model = Place
    template_name = 'place_list.html'
    context_object_name = 'places'

db_admin/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Nomade Admin</title>
</head>
<body>

    <main>
        {% block content %}{% endblock %}
    </main>

    {% block extra_js %}{% endblock %}
</body>
</html>

db_admin/templates/place_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Places</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Quiet</th>
        <th>Solo</th>
        <th>Gathering</th>
        <th>Wifi</th>
        <th>Outlet</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for place in places %}
        <tr>
          <td>{{ place.name }}</td>
          <td>{{ place.get_type_display }}</td>
          <td>{% if place.quiet %}Yes{% else %}No{% endif %}</td>
          <td>{% if place.solo %}Yes{% else %}No{% endif %}</td>
          <td>{% if place.gathering %}Yes{% else %}No{% endif %}</td>
          <td>{% if place.wifi %}Yes{% else %}No{% endif %}</td>
          <td>{% if place.outlet %}Yes{% else %}No{% endif %}</td>
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}